/**
 * @file AgbGuestApi.h
 * @brief Contract between GbaPlayer (com.recomp.gba) and game packages built as wasm2c
 *        guests (AGB_GUEST=wasm, Source/Guest generated by the game's build.ps1).
 *
 * A guest game registers itself at startup (AgbRegisterGuest, a static initializer in
 * its generated Source/Guest/AgbGuestEntry.cpp) and GbaPlayer runs it in-process on its
 * own thread through the AgbHostApi callbacks. This needs both packages in one program,
 * which is how packaged builds (Windows, Linux, consoles...) link addons; in the editor
 * the guest code is compiled out (separate DLLs) and GbaPlayer uses the native game
 * executable as a child process instead.
 *
 * A copy of this header is published into each game package (keep them in sync through
 * AGB_GUEST_API_VERSION).
 */
#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define AGB_GUEST_API_VERSION 2 /* 2: script bridge callbacks */

/* What the game needs from the player (agb_host.h); called on the game's thread. */
typedef struct AgbHostApi
{
    void* user;
    /* a finished 240x160 frame, BGR555 */
    void (*present)(void* user, const uint16_t* bgr555);
    /* blocks until the next 59.73 Hz frame; returns nonzero when the game must stop */
    int (*wait_frame)(void* user);
    /* KEYINPUT bits, pressed = 1 */
    uint32_t (*keys)(void* user);
    /* 44100 Hz interleaved stereo */
    void (*audio)(void* user, const int16_t* stereo, int frames);
    int (*load_save)(void* user, uint8_t* data, int size);
    void (*store_save)(void* user, const uint8_t* data, int size);
    /* the game data file (AgbGuestDesc.data_file in the package's Assets folder) */
    int (*read_data)(void* user, uint32_t offset, void* dst, uint32_t size);
    void (*log)(void* user, const char* line);
    /* script bridge (agb_bridge.h / agb_host.h), game thread, once per frame: the variable
     * and request descriptions, the variables' bytes, queued requests and their results */
    void (*bridge_publish)(void* user, const char* vars, const char* requests);
    void (*bridge_values)(void* user, const void* data, uint32_t size);
    int (*bridge_poll)(void* user, char* name, uint32_t name_cap, int* args, int max_args, int* nargs);
    void (*bridge_done)(void* user, int id, int result);
} AgbHostApi;

typedef struct AgbGuestDesc
{
    uint32_t api_version;    /* AGB_GUEST_API_VERSION */
    const char* package;     /* e.g. "com.recomp.khcom" */
    const char* data_file;   /* e.g. "khcom.agbdata" */
    uint32_t memory_bytes;   /* guest memory it allocates */
    /* runs the game on the calling thread until host->wait_frame asks it to stop;
     * returns 0 after a requested stop, nonzero after a failure */
    int (*run)(const AgbHostApi* host);
} AgbGuestDesc;

/* com.recomp.gba */
void AgbRegisterGuest(const AgbGuestDesc* desc);
const AgbGuestDesc* AgbFindGuest(const char* package);

#ifdef __cplusplus
}
#endif
