#!/usr/bin/env python3
"""
Generates agb_memory.s: the GBA memory regions of the agb runtime (agb_ewram, agb_iwram,
agb_io, agb_pltt, agb_vram, agb_oam, agb_sram, agb_bios) as zeroed arrays, with the decomp's
absolute-address symbols (linker-script `name = 0x...;` lines and --sym extras) as labels
at the right offsets inside them.

ROM-address symbols (0x08000000-0x09FFFFFF) are resolved to the data label that the decomp
defines for the same address (a global label ending in _<ADDR>, e.g. gUnkUs_0976D880 for
gUnk_0976D880) through a linker /alternatename directive (wasm: --alias-list for elf2wasm.py);
when there is none, the bytes are
copied from the ROM image (--rom) so the game can still read them.

Symbols whose value is a plain number rather than an address (e.g. m4a's gNumMusicPlayers)
cannot live in a region; they are reported and must be handled by the game's prelude.

Output is GNU assembler syntax for x86 COFF (assembled with clang -c).
"""
import argparse
import os
import re
import sys

REGIONS = [
    # name, base, size
    ("agb_bios", 0x00000000, 0x4000),
    ("agb_ewram", 0x02000000, 0x40000),
    ("agb_iwram", 0x03000000, 0x8000),
    ("agb_io", 0x04000000, 0x400),
    ("agb_pltt", 0x05000000, 0x400),
    ("agb_vram", 0x06000000, 0x18000),
    ("agb_oam", 0x07000000, 0x400),
    ("agb_sram", 0x0E000000, 0x10000),
]
ROM_BASE, ROM_END = 0x08000000, 0x0A000000
ROM_COPY_MAX = 0x1000

ASSIGN = re.compile(r"^\s*([A-Za-z_][\w.]*)\s*=\s*(0[xX][0-9A-Fa-f]+|\d+)\s*;", re.M)
GLOBAL = re.compile(r"^\s*\.glob(?:a)?l\s+([A-Za-z_][\w.]*)", re.M)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ldscript", help="decomp linker script with name = 0x...; lines")
    ap.add_argument("--sym", action="append", default=[], help="extra name=address")
    ap.add_argument("--labels", action="append", default=[], help="data .s file(s) defining ROM labels, or @listfile")
    ap.add_argument("--rom", help="ROM image for ROM symbols without a data label")
    ap.add_argument("--underscore", action="store_true", help="prefix symbols with _ (32-bit Windows)")
    ap.add_argument("--wasm", action="store_true", help="wasm32 object syntax (sections, .size for every symbol)")
    ap.add_argument("--alias-list", help="write ROM aliases to this file (for elf2wasm.py) instead of linker directives")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    syms = {}
    if args.ldscript:
        for name, value in ASSIGN.findall(open(args.ldscript, encoding="utf-8").read()):
            syms[name] = int(value, 0)
    for item in args.sym:
        name, value = item.split("=", 1)
        syms[name] = int(value, 0)

    label_files = []
    for item in args.labels:
        if item.startswith("@"):
            label_files += [l.strip() for l in open(item[1:], encoding="utf-8") if l.strip()]
        else:
            label_files.append(item)
    globals_by_suffix = {}
    for path in label_files:
        try:
            text = open(path, encoding="utf-8", errors="replace").read()
        except OSError:
            continue
        for g in GLOBAL.findall(text):
            m = re.search(r"_([0-9A-Fa-f]{8})$", g)
            if m:
                globals_by_suffix.setdefault(int(m.group(1), 16), []).append(g)

    rom = open(args.rom, "rb").read() if args.rom else None
    u = "_" if args.underscore else ""

    placed = {r[0]: [] for r in REGIONS}
    aliases = []
    rom_copies = []
    skipped = []
    for name, addr in sorted(syms.items(), key=lambda kv: kv[1]):
        region = next((r for r in REGIONS if r[1] <= addr < r[1] + r[2]), None)
        if region:
            placed[region[0]].append((addr - region[1], name))
            continue
        if ROM_BASE <= addr < ROM_END:
            targets = [t for t in globals_by_suffix.get(addr, []) if t != name]
            if targets:
                aliases.append((name, targets[0]))
            else:
                rom_copies.append((addr, name))
            continue
        skipped.append((name, addr))

    out = []
    w = out.append
    wasm = args.wasm

    def label(name, size):
        if not wasm:
            w(f"\t.globl {u}{name}")
            w(f"{u}{name}:")
            return
        w(f"\t.globl {name}")
        w(f"{name}:")
        w(f"\t.size {name}, {size:#x}")

    w("/* Generated by com.recomp.gba/Runtime/tools/gen_memory.py. Do not edit. */")
    if not wasm:
        w("\t.bss")
    for rname, base, size in REGIONS:
        w("")
        if wasm:
            w(f'\t.section .bss.{rname},"",@')
        w("\t.p2align 5")
        label(rname, size)
        cur = 0
        offs = [o for o, _ in placed[rname]]
        for off, name in placed[rname]:
            if off > cur:
                w(f"\t.space {off - cur:#x}")
                cur = off
            nxt = next((o for o in offs if o > off), size)
            label(name, nxt - off)
        if size > cur:
            w(f"\t.space {size - cur:#x}")

    if rom_copies:
        if rom is None:
            sys.exit("gen_memory: ROM symbols without a data label need --rom: " + ", ".join(n for _, n in rom_copies))
        w("")
        w('\t.section .rodata.agb_rom_copies,"",@' if wasm else '\t.section .rdata,"dr"')
        for i, (addr, name) in enumerate(rom_copies):
            nxt = rom_copies[i + 1][0] if i + 1 < len(rom_copies) else ROM_END
            off = addr - ROM_BASE
            length = max(1, min(ROM_COPY_MAX, nxt - addr, len(rom) - off))
            w("\t.p2align 2")
            label(name, length)
            data = rom[off:off + length]
            for j in range(0, len(data), 32):
                w("\t.byte " + ",".join(str(b) for b in data[j:j + 32]))

    if args.alias_list is not None:
        # "alias target" lines: elf2wasm.py adds each alias as a second label on its target
        with open(args.alias_list, "w", encoding="utf-8", newline="\n") as f:
            f.write("".join(f"{name} {target}\n" for name, target in aliases))
    elif aliases:
        w("")
        w("\t.section .drectve,\"yn\"")
        for name, target in aliases:
            w(f"\t.ascii \" /alternatename:{u}{name}={u}{target}\"")

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")

    print(f"gen_memory: {sum(len(v) for v in placed.values())} region labels, {len(aliases)} ROM aliases, "
          f"{len(rom_copies)} ROM copies -> {args.out}")
    for name, addr in skipped:
        print(f"gen_memory: note: {name} = {addr:#x} is not an address; define it in the game prelude")


if __name__ == "__main__":
    main()
