#!/usr/bin/env python3
"""
Publishes a wasm2c guest build (AGB_GUEST=wasm) into its game package, which is how the
game reaches every engine target: the package becomes a small native addon whose sources
the editor and the console makefiles compile with each target's own toolchain.

  <package>/Source/<Plugin>.cpp        addon entry (no nodes; registers nothing itself)
  <package>/Source/Guest/              translated game (agb_guest_*.c, headers), the wasm2c
                                       runtime and in-process bridge, AgbGuestEntry.cpp
                                       (registers the game with com.recomp.gba's GbaPlayer)
  <package>/Assets/<name>.agbdata      game data, shipped loose by the packager

Every C/C++ file is wrapped in `#if !EDITOR`: in the editor the addons are separate DLLs
and GbaPlayer runs the native executable instead (see AgbGuestApi.h).

Usage: publish_guest.py --package-dir D --package ID --name N --memory BYTES --runtime RT
                        --gba-source DIR --wabt-include DIR --w2c-dir DIR --data FILE
"""
import argparse
import os
import re
import shutil

BUILD_HEADER = """/* Generated by publish_guest.py: wasm2c runtime configuration. */
#ifndef AGBW_BUILD_H
#define AGBW_BUILD_H
#define WASM_RT_USE_MMAP 0
#define WASM_RT_MEMCHECK_BOUNDS_CHECK 1
#define WASM_RT_NONCONFORMING_UNCHECKED_STACK_EXHAUSTION 1
#define WASM_RT_SKIP_SIGNAL_RECOVERY 1
#endif
"""

ENTRY = """/* Generated by publish_guest.py: registers {package} with GbaPlayer (com.recomp.gba). */
#include "AgbGuestApi.h"

extern "C" int agbw_bridge_run(const AgbHostApi* host);

static const AgbGuestDesc kGuest = {{
    AGB_GUEST_API_VERSION, "{package}", "{data_file}", {memory}u, agbw_bridge_run,
}};

static int sRegistered = (AgbRegisterGuest(&kGuest), 0);
"""

PLUGIN = """/* Written by publish_guest.py: native addon entry of {package} (game code only; the
 * GbaPlayer node lives in com.recomp.gba). Same content on every build and no game data,
 * so it is committed: the addon compiles before Source/Guest/ has been generated. */
#include "Plugins/PolyphasePluginAPI.h"
#include "Plugins/PolyphaseEngineAPI.h"

static int OnLoad(PolyphaseEngineAPI* api)
{{
    (void)api;
    return 0;
}}

static void OnUnload()
{{
}}

static void RegisterTypes(void* nodeFactory)
{{
    (void)nodeFactory;
}}

static void RegisterScriptFuncs(lua_State* L)
{{
    (void)L;
}}

static int FillDesc(PolyphasePluginDesc* desc)
{{
    desc->apiVersion = OCTAVE_PLUGIN_API_VERSION;
    desc->pluginName = "{package}";
    desc->pluginVersion = "1.0.0";
    desc->OnLoad = OnLoad;
    desc->OnUnload = OnUnload;
    desc->RegisterTypes = RegisterTypes;
    desc->RegisterScriptFuncs = RegisterScriptFuncs;
    desc->RegisterEditorUI = nullptr;
    desc->OnEditorPreInit = nullptr;
    desc->OnEditorReady = nullptr;
    return 0;
}}

#if EDITOR
extern "C" OCTAVE_PLUGIN_API int PolyphasePlugin_GetDesc(PolyphasePluginDesc* desc)
{{
    return FillDesc(desc);
}}
#else
extern "C" int PolyphasePlugin_GetDesc_{symbol}(PolyphasePluginDesc* desc)
{{
    return FillDesc(desc);
}}
#endif
"""


def write_if_changed(path, data):
    if isinstance(data, str):
        data = data.encode("utf-8")
    try:
        if open(path, "rb").read() == data:
            return
    except OSError:
        pass
    with open(path, "wb") as f:
        f.write(data)


def wrap_source(text, build_header=True):
    head = "/* Published by publish_guest.py: game code for packaged builds only (AgbGuestApi.h). */\n#if !EDITOR\n"
    if build_header:
        head += '#include "agbw_build.h"\n'
    return head + text + ("\n" if not text.endswith("\n") else "") + "#endif /* !EDITOR */\n"


def main():
    ap = argparse.ArgumentParser()
    for opt in ("package-dir", "package", "name", "memory", "runtime", "gba-source", "wabt-include", "w2c-dir", "data"):
        ap.add_argument("--" + opt, required=True)
    a = ap.parse_args()

    guest = os.path.join(a.package_dir, "Source", "Guest")
    os.makedirs(guest, exist_ok=True)
    keep = set()

    def put(name, data):
        keep.add(name)
        write_if_changed(os.path.join(guest, name), data)

    put("agbw_build.h", BUILD_HEADER)
    # translated game
    for f in sorted(os.listdir(a.w2c_dir)):
        src = os.path.join(a.w2c_dir, f)
        if re.fullmatch(r"agb_guest_\d+\.c", f):
            put(f, wrap_source(open(src, encoding="utf-8").read()))
        elif f in ("agb_guest.h", "agb_guest-impl.h", "agbw_config.h"):
            put(f, open(src, "rb").read())
    # wasm2c runtime, guest glue, in-process bridge
    for f in ("agbw.h", "agbw_mem_ops.h", "agbw_ops.h"):
        put(f, open(os.path.join(a.runtime, "wasm", f), "rb").read())
    for f in ("agbw_rt.c", "agbw_guest.c", "agbw_bridge.c"):
        put(f, wrap_source(open(os.path.join(a.runtime, "wasm", f), encoding="utf-8").read()))
    put("agb_host.h", open(os.path.join(a.runtime, "include", "agb_host.h"), "rb").read())
    put("AgbGuestApi.h", open(os.path.join(a.gba_source, "AgbGuestApi.h"), "rb").read())
    for f in ("wasm-rt.h", "wasm-rt-exceptions.h"):
        put(f, open(os.path.join(a.wabt_include, f), "rb").read())
    data_file = a.name + ".agbdata"
    put("AgbGuestEntry.cpp", wrap_source(ENTRY.format(package=a.package, data_file=data_file, memory=a.memory),
                                         build_header=False))
    # stale files from an earlier publish (e.g. a different number of wasm2c outputs)
    for f in os.listdir(guest):
        if f not in keep:
            os.remove(os.path.join(guest, f))

    # addon entry
    plugin = "".join(p.capitalize() for p in a.package.split(".")) + ".cpp"
    write_if_changed(os.path.join(a.package_dir, "Source", plugin),
                     PLUGIN.format(package=a.package, symbol=a.package.replace(".", "_")))
    # game data, shipped loose with the package's Assets
    assets = os.path.join(a.package_dir, "Assets")
    os.makedirs(assets, exist_ok=True)
    dst = os.path.join(assets, data_file)
    if not os.path.exists(dst) or os.path.getsize(dst) != os.path.getsize(a.data) or \
            open(dst, "rb").read() != open(a.data, "rb").read():
        shutil.copyfile(a.data, dst)
    print(f"publish_guest: {a.package} -> {guest} and {dst}")


if __name__ == "__main__":
    main()
